CIVL v1.7 of 2016-03-31 -- http://vsl.cis.udel.edu/civl

Violation 0 encountered at depth 53:
CIVL execution violation in p1 (id = 1) (kind: UNDEFINED_VALUE, certainty: PROVEABLE)
at c_ex10.c:59.11-18 "used_id":
attempt to read uninitialized variable used_id

Input:
  _gen_argc=X__gen_argc
  _gen_argv=X__gen_argv
  _mpi_nprocs=2
  _mpi_nprocs_lo=1
  _mpi_nprocs_hi=X__mpi_nprocs_hi
Context:
  (X__gen_argc-9)<=0
  0<=(fileLength("CIVL_stdin\0")-1)
  0<=(SIZEOF_INT-1)
  0<=(X__gen_argc-1)
  0<=(X__mpi_nprocs_hi-2)
Call stacks:
process p0 (id=0):
  main at MPITransformer:0.-1-20 "$parfor (int i: 0 ..." inserted by MPITransformer.$parfor MPI_Process before op.h:21.1-10 "Operation" included from civlc.cvh:8.8-14 "<op.h>" included from stdio.cvl:10.10-21 "<civlc.cvh>"
process p1 (id=1):
  _gen_main at c_ex10.c:59.8-10 "if" called from
  _mpi_process at GeneralTransformer:0.-1-20 "_gen_argc, &(_gen_..." inserted by GeneralTransformer.new main function before c_ex10.c:32.13-17 "argc" called from
  _par_proc0 at MPITransformer:0.-1-0 "i" inserted by MPITransformer.function call _mpi_process before op.h:21.1-10 "Operation" included from civlc.cvh:8.8-14 "<op.h>" included from stdio.cvl:10.10-21 "<civlc.cvh>"
process p2 (id=2):
  _par_proc0 at MPITransformer:0.-1-0 "i" inserted by MPITransformer.function call _mpi_process before op.h:21.1-10 "Operation" included from civlc.cvh:8.8-14 "<op.h>" included from stdio.cvl:10.10-21 "<civlc.cvh>"

Logging new entry 0, writing trace to CIVLREP/c_ex10_0.trace
Terminating search after finding 1 violation.

=== Command ===
civl verify -input_mpi_nprocs=2 examples/mpi/c_ex10.c 

=== Stats ===
   time (s)            : 160.55
   memory (bytes)      : 502792192
   max process count   : 3
   states              : 107
   states saved        : 53
   state matches       : 0
   transitions         : 106
   trace steps         : 52
   valid calls         : 555
   provers             : cvc3
   prover calls        : 3

=== Result ===
The program MAY NOT be correct.  See CIVLREP/c_ex10_log.txt
