CIVL v1.7 of 2016-03-31 -- http://vsl.cis.udel.edu/civl
1. Curr_Bound = 0

After assigning the nextStack = 51
2. New_Bound = 1

2. NextStack-Size = 0


Violation 0 encountered at depth 12:
CIVL execution violation in p0(id=0) (kind: ASSERTION_VIOLATION, certainty: PROVEABLE)
at spawnBad.cvl:23.2-17 "$assert(s1==s2)":

Assertion: (s1==s2)
        -> 45==0
        -> false

Input:
  N=10
Context:
  true
Call stacks:
process p0 (id=0):
  main at spawnBad.cvl:23.2-9 "$assert"
process p1 (id=1):
  terminated
process p2 (id=2):
  f2 at spawnBad.cvl:15.2-4 "s2"

Logging new entry 0, writing trace to CIVLREP/spawnBad_0.trace
Terminating search after finding 1 violation.

=== Command ===
civl verify examples/concurrency/spawnBad.cvl 

=== Stats ===
   time (s)            : 55.72
   memory (bytes)      : 502792192
   max process count   : 3
   states              : 882
   states saved        : 170
   state matches       : 190
   transitions         : 1072
   trace steps         : 359
   valid calls         : 4
   provers             : cvc3
   prover calls        : 0

=== Result ===
The program MAY NOT be correct.  See CIVLREP/spawnBad_log.txt
